"""
LLM-enhanced code generation module.

This module provides intelligent code generation capabilities using LLM
to generate well-documented, type-annotated Python code for API tests.
"""
import json
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from flowgenius.llm.base import LLMProvider
from flowgenius.llm.config import LLMConfig
from flowgenius.llm.prompt_templates import (
    GENERATE_API_CLASS_PROMPT,
    GENERATE_TEST_CASE_PROMPT,
    GENERATE_DOCSTRING_PROMPT,
    truncate_json_for_prompt,
)
from flowgenius.models.api import APIEndpoint
from flowgenius.models.assertion import AssertionSet
from flowgenius.models.correlation import CorrelationChain
from flowgenius.models.traffic import TrafficFlow
from flowgenius.utils.logger import get_logger
from flowgenius.utils.jsonpath import extract_jsonpath


@dataclass
class GeneratedCode:
    """Represents generated code with metadata.

    Attributes:
        code: The generated code string
        language: Programming language
        description: Description of the generated code
        imports: Required import statements
        dependencies: Required external dependencies
    """

    code: str
    language: str = "python"
    description: str = ""
    imports: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)


class LLMCodeGenerator:
    """LLM-enhanced code generator.

    This class uses LLM to generate well-documented, semantic
    Python code for API objects and test cases.
    """

    def __init__(
        self,
        llm_provider: Optional[LLMProvider] = None,
        config: Optional[LLMConfig] = None
    ):
        """Initialize the LLM code generator.

        Args:
            llm_provider: LLM provider instance
            config: LLM configuration
        """
        self.llm_provider = llm_provider
        self.config = config or LLMConfig()
        self.logger = get_logger("flowgenius.llm.code_generator")

    def generate_api_class(
        self,
        flow: TrafficFlow,
        endpoint: Optional[APIEndpoint] = None,
        base_url: str = "",
        style: str = "pythonic"
    ) -> GeneratedCode:
        """Generate an API object class using LLM.

        Args:
            flow: TrafficFlow to generate class for
            endpoint: Optional API endpoint definition
            base_url: Base URL for the API
            style: Code style ("pythonic", "verbose")

        Returns:
            GeneratedCode with the API class
        """
        if not self.llm_provider:
            return self._fallback_api_class(flow, endpoint, base_url)

        try:
            # Extract information from flow
            path = self._extract_path(flow, endpoint)
            method = flow.request.method
            params = self._extract_params(flow, endpoint)
            response_schema = self._extract_response_schema(flow, endpoint)
            business_logic = self._infer_business_logic(flow, endpoint)

            prompt = GENERATE_API_CLASS_PROMPT.format(
                path=path,
                method=method,
                params=json.dumps(params, ensure_ascii=False, indent=2),
                response_schema=response_schema,
                business_logic=business_logic,
            )

            code = self.llm_provider.generate(prompt)

            # Extract code from markdown if needed
            code = self._extract_code_from_markdown(code)

            return GeneratedCode(
                code=code,
                language="python",
                description=f"API class for {method} {path}",
                imports=["requests", "typing"],
                dependencies=["requests"],
            )

        except Exception as e:
            self.logger.error(f"LLM code generation failed: {e}")
            return self._fallback_api_class(flow, endpoint, base_url)

    def _fallback_api_class(
        self,
        flow: TrafficFlow,
        endpoint: Optional[APIEndpoint],
        base_url: str
    ) -> GeneratedCode:
        """Generate API class using fallback rules.

        Args:
            flow: TrafficFlow
            endpoint: API endpoint
            base_url: Base URL

        Returns:
            GeneratedCode with rule-based API class
        """
        from urllib.parse import urlparse

        if not base_url:
            parsed = urlparse(flow.request.url)
            base_url = f"{parsed.scheme}://{parsed.netloc}"

        path = self._extract_path(flow, endpoint)
        class_name = self._generate_class_name(flow, endpoint)
        method_name = flow.request.method.lower()

        code = f'''"""
API object for {path}
Automatically generated by FlowGenius SmartAdapter
"""

import requests
from typing import Any, Dict, Optional


class {class_name}:
    """API endpoint for {path}."""

    def __init__(self, base_url: str = "{base_url}", timeout: int = 30) -> None:
        """Initialize {class_name}.

        Args:
            base_url: Base URL for the API
            timeout: Request timeout in seconds
        """
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.session = requests.Session()

    def {method_name}(
        self,
        headers: Optional[Dict[str, str]] = None,
        params: Optional[Dict[str, Any]] = None,
        body: Optional[Dict[str, Any]] = None,
        **kwargs
    ) -> requests.Response:
        """Send a {flow.request.method} request to {path}.

        Args:
            headers: Request headers
            params: Query parameters
            body: Request body

        Returns:
            Response object
        """
        url = f"{{self.base_url}}{path}"

        request_headers = {{}}
        if headers:
            request_headers.update(headers)

        response = self.session.{method_name}(
            url,
            headers=request_headers,
            params=params,
            json=body,
            timeout=self.timeout,
            **kwargs
        )

        return response
'''

        return GeneratedCode(
            code=code,
            language="python",
            description=f"API class for {flow.request.method} {path}",
            imports=["requests", "typing"],
            dependencies=["requests"],
        )

    def generate_test_case(
        self,
        flow: TrafficFlow,
        assertion_set: AssertionSet,
        correlation_chain: Optional[CorrelationChain] = None,
        business_logic: Optional[str] = None,
        language: str = "zh"
    ) -> GeneratedCode:
        """Generate a test case using LLM.

        Args:
            flow: TrafficFlow to generate test for
            assertion_set: AssertionSet with validations
            correlation_chain: Optional correlation chain
            business_logic: Business logic description
            language: Language for comments ("zh", "en")

        Returns:
            GeneratedCode with the test case
        """
        if not self.llm_provider:
            return self._fallback_test_case(flow, assertion_set, correlation_chain)

        try:
            path = flow.request.url
            method = flow.request.method

            # Build request params summary
            request_params = {
                "headers": dict(list(flow.request.headers.items())[:5]),  # Limit
                "query_params": flow.request.query_params,
                "body": flow.request.get_body_json(),
            }

            # Build assertions summary
            assertions = []
            for assertion in assertion_set.assertions:
                assertions.append({
                    "type": assertion.assertion_type.value,
                    "description": assertion.description,
                    "path": assertion.actual_jsonpath,
                    "expected": assertion.expected_value,
                })

            # Build correlation vars
            correlation_vars = []
            if correlation_chain:
                for correlation in correlation_chain.correlations:
                    correlation_vars.append({
                        "name": correlation.variable_name,
                        "source_path": correlation.response_jsonpath,
                        "target_location": correlation.request_location,
                    })

            prompt = GENERATE_TEST_CASE_PROMPT.format(
                path=path,
                method=method,
                request_params=json.dumps(request_params, ensure_ascii=False, indent=2),
                assertions=json.dumps(assertions, ensure_ascii=False, indent=2),
                correlation_vars=json.dumps(correlation_vars, ensure_ascii=False, indent=2),
                business_logic=business_logic or self._infer_business_logic(flow),
            )

            code = self.llm_provider.generate(prompt)
            code = self._extract_code_from_markdown(code)

            return GeneratedCode(
                code=code,
                language="python",
                description=f"Test case for {method} {path}",
                imports=["pytest", "requests"],
                dependencies=["pytest", "requests"],
            )

        except Exception as e:
            self.logger.error(f"LLM test case generation failed: {e}")
            return self._fallback_test_case(flow, assertion_set, correlation_chain)

    def _fallback_test_case(
        self,
        flow: TrafficFlow,
        assertion_set: AssertionSet,
        correlation_chain: Optional[CorrelationChain] = None
    ) -> GeneratedCode:
        """Generate test case using fallback rules.

        Args:
            flow: TrafficFlow
            assertion_set: AssertionSet
            correlation_chain: Optional correlation chain

        Returns:
            GeneratedCode with rule-based test case
        """
        test_name = self._generate_test_name(flow)

        code = f'''    def {test_name}(self, base_url, session):
        """测试 {flow.request.method} {flow.request.url}"""

        # 发送请求
        response = session.{flow.request.method.lower()}(
            base_url + "{flow.request.url}",
        )

        # 断言
'''

        # Add assertions
        for assertion in assertion_set.assertions[:5]:  # Limit to 5
            code += f"        # {assertion.description}\n"
            assertion_code = assertion.get_assertion_code()
            if assertion_code:
                code += f"        {assertion_code}\n"

        return GeneratedCode(
            code=code,
            language="python",
            description=f"Test case for {flow.request.method} {flow.request.url}",
            imports=["pytest", "requests"],
            dependencies=["pytest", "requests"],
        )

    def generate_docstring(
        self,
        api_path: str,
        method: str,
        params: Dict[str, Any],
        response_summary: Dict[str, Any],
        business_logic: Optional[str] = None
    ) -> str:
        """Generate a docstring using LLM.

        Args:
            api_path: API path
            method: HTTP method
            params: Parameters dictionary
            response_summary: Response structure summary
            business_logic: Business logic description

        Returns:
            Generated docstring
        """
        if not self.llm_provider:
            return self._fallback_docstring(api_path, method, params, response_summary)

        try:
            prompt = GENERATE_DOCSTRING_PROMPT.format(
                path=api_path,
                method=method,
                params=json.dumps(params, ensure_ascii=False, indent=2),
                response_summary=json.dumps(response_summary, ensure_ascii=False, indent=2),
                business_logic=business_logic or "未提供",
            )

            docstring = self.llm_provider.generate(prompt)

            # Clean up the docstring
            docstring = docstring.strip()
            if docstring.startswith('"""') or docstring.startswith("'''"):
                docstring = docstring[3:]
            if docstring.endswith('"""') or docstring.endswith("'''"):
                docstring = docstring[:-3]

            return docstring.strip()

        except Exception as e:
            self.logger.warning(f"Failed to generate docstring: {e}")
            return self._fallback_docstring(api_path, method, params, response_summary)

    def _fallback_docstring(
        self,
        api_path: str,
        method: str,
        params: Dict[str, Any],
        response_summary: Dict[str, Any]
    ) -> str:
        """Generate a fallback docstring.

        Args:
            api_path: API path
            method: HTTP method
            params: Parameters
            response_summary: Response summary

        Returns:
            Basic docstring
        """
        return f"""{method} {api_path}

Args:
    params: 请求参数

Returns:
    Response 对象
"""

    def generate_test_module(
        self,
        flows: List[TrafficFlow],
        assertion_sets: Dict[str, AssertionSet],
        base_url: str = "",
        group_by_endpoint: bool = True
    ) -> GeneratedCode:
        """Generate a complete test module using LLM.

        Args:
            flows: List of TrafficFlow objects
            assertion_sets: Dictionary of AssertionSets
            base_url: Base URL for the API
            group_by_endpoint: Whether to group tests by endpoint

        Returns:
            GeneratedCode with the complete test module
        """
        lines = [
            '"""',
            'API test module',
            'Generated by FlowGenius SmartAdapter with LLM enhancement',
            '"""',
            '',
            'import pytest',
            'import requests',
            'from typing import Any, Dict, Optional',
            '',
        ]

        # Generate test classes
        if group_by_endpoint:
            from collections import defaultdict
            endpoint_flows = defaultdict(list)
            for flow in flows:
                key = (flow.request.method, flow.request.url)
                endpoint_flows[key].append(flow)

            for (method, url), endpoint_flow_list in endpoint_flows.items():
                class_name = self._generate_class_name_from_url(url, method)
                lines.append('')
                lines.append(f'class {class_name}:')
                lines.append(f'    """Test cases for {method} {url}"""')
                lines.append('')

                # Generate test cases for each flow
                for flow in endpoint_flow_list:
                    assertion_set = assertion_sets.get(flow.flow_id)
                    if assertion_set:
                        test_code = self._fallback_test_case(flow, assertion_set)
                        lines.append(test_code.code)

        return GeneratedCode(
            code='\n'.join(lines),
            language="python",
            description="Complete test module",
            imports=["pytest", "requests", "typing"],
            dependencies=["pytest", "requests"],
        )

    # Helper methods

    def _extract_path(self, flow: TrafficFlow, endpoint: Optional[APIEndpoint]) -> str:
        """Extract the API path."""
        if endpoint:
            return endpoint.path
        from urllib.parse import urlparse
        parsed = urlparse(flow.request.url)
        return parsed.path or "/"

    def _extract_params(self, flow: TrafficFlow, endpoint: Optional[APIEndpoint]) -> Dict[str, Any]:
        """Extract parameters from flow and endpoint."""
        params = {
            "query": flow.request.query_params,
            "headers": dict(list(flow.request.headers.items())[:5]),
        }

        body = flow.request.get_body_json()
        if body:
            params["body"] = body

        if endpoint and endpoint.parameters:
            params["endpoint_params"] = [
                {"name": p.name, "in": p.in_, "required": p.required}
                for p in endpoint.parameters[:10]  # Limit
            ]

        return params

    def _extract_response_schema(self, flow: TrafficFlow, endpoint: Optional[APIEndpoint]) -> str:
        """Extract response schema."""
        response_data = flow.response.get_body_json()
        if response_data:
            return truncate_json_for_prompt(response_data, 1000)

        if endpoint:
            success_response = endpoint.get_success_response()
            if success_response and success_response.schema:
                return json.dumps(success_response.schema, indent=2)

        return "{}"

    def _infer_business_logic(self, flow: TrafficFlow, endpoint: Optional[APIEndpoint] = None) -> str:
        """Infer business logic from the API."""
        if endpoint and endpoint.summary:
            return endpoint.summary

        # Try to infer from URL path
        from urllib.parse import urlparse
        parsed = urlparse(flow.request.url)
        path_parts = [p for p in parsed.path.split('/') if p and not p.startswith('{')]

        method_actions = {
            "GET": "查询",
            "POST": "创建",
            "PUT": "更新",
            "DELETE": "删除",
            "PATCH": "部分更新",
        }

        action = method_actions.get(flow.request.method, "操作")
        resource = path_parts[-1] if path_parts else "资源"

        return f"{action}{resource}"

    def _generate_class_name(self, flow: TrafficFlow, endpoint: Optional[APIEndpoint]) -> str:
        """Generate a class name for the API."""
        if endpoint:
            return endpoint.get_class_name()

        from urllib.parse import urlparse
        parsed = urlparse(flow.request.url)
        path_parts = [p for p in parsed.path.split('/') if p and not p.startswith('{')]

        if path_parts:
            resource = path_parts[-1].capitalize()
            return f"Api{resource}"

        return "ApiEndpoint"

    def _generate_test_name(self, flow: TrafficFlow) -> str:
        """Generate a test method name."""
        from urllib.parse import urlparse
        parsed = urlparse(flow.request.url)
        path_parts = [p for p in parsed.path.split('/') if p and not p.startswith('{')]

        method = flow.request.method.lower()
        if path_parts:
            resource = path_parts[-1]
            return f"test_{method}_{resource}"

        return f"test_{method}_api"

    def _generate_class_name_from_url(self, url: str, method: str) -> str:
        """Generate a class name from URL."""
        from urllib.parse import urlparse
        parsed = urlparse(url)
        path_parts = [p for p in parsed.path.split('/') if p and not p.startswith('{')]

        if path_parts:
            resource = path_parts[-1].capitalize()
            return f"Test{resource}"

        return "TestAPI"

    def _extract_code_from_markdown(self, text: str) -> str:
        """Extract code from markdown code blocks.

        Args:
            text: Text that may contain markdown code blocks

        Returns:
            Extracted code string
        """
        # Check for markdown code block
        if "```python" in text:
            start = text.find("```python") + 9
            end = text.find("```", start)
            return text[start:end].strip()
        elif "```" in text:
            start = text.find("```") + 3
            # Skip language identifier on first line
            first_newline = text.find("\n", start)
            if first_newline > 0:
                start = first_newline + 1
            end = text.find("```", start)
            return text[start:end].strip()

        return text