"""
API object layer code generation.
"""
import logging
from typing import Any, Dict, List, Optional

from flowgenius.models.api import APIEndpoint
from flowgenius.models.traffic import TrafficFlow
from flowgenius.models.correlation import CorrelationChain
from flowgenius.utils.logger import get_logger


class APIObjectGenerator:
    """Generates API object classes from traffic and Swagger definitions."""

    def __init__(self):
        """Initialize API object generator."""
        self.logger = get_logger("flowgenius.api_object_generator")

    def generate_class(
        self,
        endpoint: APIEndpoint,
        base_url: str = "https://api.example.com"
    ) -> str:
        """
        Generate an API object class.

        Args:
            endpoint: APIEndpoint definition
            base_url: Base URL for the API

        Returns:
            Generated Python class code
        """
        class_name = endpoint.get_class_name()
        method_name = endpoint.get_method_name()

        # Get required parameters
        required_params = endpoint.get_required_params()

        # Build the class
        lines = [
            '"""',
            f'API object for {endpoint.path}',
            f'Automatically generated by FlowGenius SmartAdapter',
            '"""',
            '',
            'import requests',
            'from typing import Any, Dict, Optional',
            '',
            ''
        ]

        # Class definition
        lines.append(f'class {class_name}:')
        lines.append('    """')
        lines.append(f'    {endpoint.summary or endpoint.description or f"API endpoint for {endpoint.path}"}')
        lines.append('    """')
        lines.append('')
        lines.append(f'    def __init__(self, base_url: str = "{base_url}"):')
        lines.append('        """')
        lines.append(f'        Initialize {class_name}.')
        lines.append('')
        lines.append('        Args:')
        lines.append('            base_url: Base URL for the API')
        lines.append('        """')
        lines.append('        self.base_url = base_url.rstrip("/")')
        lines.append('        self.session = requests.Session()')
        lines.append('')

        # Generate method
        lines.append(f'    def {method_name}(')
        lines.append('        self,')

        # Add required parameters as method arguments
        param_args = []
        for param in required_params:
            if param.in_ in ("path", "query"):
                param_name = param.name
                param_type = self._get_python_type(param.type)
                default_value = f' = None' if not param.required else ''
                param_args.append(f'        {param_name}: {param_type}{default_value}')

        # Add optional arguments
        lines.append('        headers: Optional[Dict[str, str]] = None,')
        lines.append('        params: Optional[Dict[str, Any]] = None,')
        lines.append('        body: Optional[Dict[str, Any]] = None,')
        lines.append('        **kwargs')
        lines.append('    ) -> requests.Response:')
        lines.append('        """')
        lines.append(f'        Send a {endpoint.method} request to {endpoint.path}.')
        lines.append('')
        lines.append('        Returns:')
        lines.append('            Response object')
        lines.append('        """')

        # Build URL
        url_path = endpoint.path
        for param in required_params:
            if param.in_ == "path":
                url_path = url_path.replace(f'{{{param.name}}}', f'{{{param.name}}}')

        lines.append(f'        url = f"{{self.base_url}}{url_path}"')

        # Add parameters to URL
        for param in required_params:
            if param.in_ == "query":
                lines.append(f'        if {param.name} is not None:')
                lines.append(f'            params = params or {{}}')
                lines.append(f'            params["{param.name}"] = {param_name}')

        # Add path parameters formatting
        for param in required_params:
            if param.in_ == "path":
                lines.append(f'        url = url.format({param_name}={param_name})')

        lines.append('')
        lines.append('        # Merge headers')
        lines.append('        request_headers = {}')
        lines.append('        if headers:')
        lines.append('            request_headers.update(headers)')
        lines.append('')
        lines.append('        # Make the request')
        lines.append(f'        response = self.session.{endpoint.method.lower()}(')
        lines.append('            url,')
        lines.append('            headers=request_headers,')
        lines.append('            params=params,')
        lines.append('            json=body,')
        lines.append('            **kwargs')
        lines.append('        )')
        lines.append('')
        lines.append('        return response')
        lines.append('')

        return '\n'.join(lines)

    def _get_python_type(self, swagger_type: Optional[str]) -> str:
        """Map Swagger type to Python type."""
        type_mapping = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "array": "list",
            "object": "Dict[str, Any]"
        }
        return type_mapping.get(swagger_type, "Any")

    def generate_from_flow(self, flow: TrafficFlow, base_url: str = "") -> str:
        """
        Generate API object from a traffic flow.

        Args:
            flow: TrafficFlow object
            base_url: Base URL (inferred from flow if not provided)

        Returns:
            Generated Python class code
        """
        # Infer base URL from flow URL
        if not base_url:
            from urllib.parse import urlparse
            parsed = urlparse(flow.request.url)
            base_url = f"{parsed.scheme}://{parsed.netloc}"

        # Create a mock endpoint
        from flowgenius.models.api import APIEndpoint
        endpoint = APIEndpoint(
            path=flow.request.url.replace(base_url, ""),
            method=flow.request.method,
            summary=f"API endpoint for {flow.request.url}"
        )

        return self.generate_class(endpoint, base_url)

    def generate_module(
        self,
        flows: List[TrafficFlow],
        base_url: Optional[str] = None
    ) -> str:
        """
        Generate a module with multiple API object classes.

        Args:
            flows: List of TrafficFlow objects
            base_url: Base URL for all endpoints

        Returns:
            Generated Python module code
        """
        # Group flows by unique URL paths
        unique_flows = {}
        for flow in flows:
            from urllib.parse import urlparse
            parsed = urlparse(flow.request.url)
            path = parsed.path

            # Only keep one flow per unique URL+method combination
            key = (path, flow.request.method)
            if key not in unique_flows:
                unique_flows[key] = flow

        # Generate classes
        lines = [
            '"""',
            'API object layer',
            'Automatically generated by FlowGenius SmartAdapter',
            '"""',
            '',
            'import requests',
            'from typing import Any, Dict, Optional',
            '',
            ''
        ]

        for flow in unique_flows.values():
            class_code = self.generate_from_flow(flow, base_url or "")
            lines.append(class_code)

        return '\n'.join(lines)

    def generate_with_correlations(
        self,
        flow: TrafficFlow,
        chain: CorrelationChain,
        base_url: str = ""
    ) -> str:
        """
        Generate API object class with correlation support.

        Args:
            flow: TrafficFlow object
            chain: CorrelationChain with variable references
            base_url: Base URL

        Returns:
            Generated Python class code with variable substitution
        """
        # Get variable references for this flow
        var_refs = chain.get_flow_variables(flow.flow_id)

        # Generate base class
        class_code = self.generate_from_flow(flow, base_url)

        # Add variable substitution logic if needed
        if var_refs:
            # Insert variable extraction method
            extract_method = self._generate_extract_method(chain)
            class_code = class_code.replace('    def __init__(self', f'    def _extract_variables(self, response_data: Dict[str, Any]) -> Dict[str, str]:\n        """Extract variables from response data."""\n        variables = {{}}\n{self._generate_extract_logic(chain)}\n        return variables\n\n    def __init__(self')

        return class_code

    def _generate_extract_method(self, chain: CorrelationChain) -> str:
        """Generate variable extraction method."""
        lines = ['        """', '        Extract variables from response.', '        """', '        from flowgenius.utils.jsonpath import extract_jsonpath', '']
        return '\n'.join(lines)

    def _generate_extract_logic(self, chain: CorrelationChain) -> str:
        """Generate extraction logic for all variables."""
        lines = []
        for flow_id in chain.flow_ids:
            extraction_rules = chain.get_extraction_rules(flow_id)
            for rule in extraction_rules:
                lines.append(f'        variables["{rule.variable_name}"] = extract_jsonpath(response_data, "{rule.source_jsonpath}")')
        return '\n'.join(lines)