"""
Configuration file generation.
"""
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from flowgenius.utils.logger import get_logger


class ConfigGenerator:
    """Generates configuration files for test projects."""

    def __init__(self):
        """Initialize config generator."""
        self.logger = get_logger("flowgenius.config_generator")

    def generate_config_py(
        self,
        base_url: str = "https://api.example.com",
        env_config: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate config.py file.

        Args:
            base_url: Base URL for API
            env_config: Optional environment-specific configuration

        Returns:
            Generated config.py content
        """
        lines = [
            '"""',
            'Configuration file for API tests',
            'Automatically generated by FlowGenius SmartAdapter',
            '"""',
            '',
            'import os',
            'from typing import Dict, Any',
            ''
        ]

        # Base URL configuration
        lines.append(f'# API Base URL')
        lines.append(f'BASE_URL = os.getenv("API_BASE_URL", "{base_url}")')
        lines.append('')

        # Environment configuration
        if env_config:
            lines.append(f'# Environment configuration')
            lines.append(f'ENV = os.getenv("ENV", "production")')
            lines.append('')

            lines.append('# Environment-specific settings')
            lines.append('ENV_CONFIG: Dict[str, Dict[str, Any]] = {')

            for env_name, config in env_config.items():
                lines.append(f'    "{env_name}": {{')

                for key, value in config.items():
                    if isinstance(value, str):
                        lines.append(f'        "{key}": "{value}",')
                    elif isinstance(value, bool):
                        lines.append(f'        "{key}": {str(value).lower()},')
                    else:
                        lines.append(f'        "{key}": {value},')

                lines.append('    },')

            lines.append('}')
            lines.append('')

        # Test configuration
        lines.append('# Test configuration')
        lines.append('TIMEOUT = 30  # Request timeout in seconds')
        lines.append('RETRY_COUNT = 3  # Number of retries on failure')
        lines.append('DEBUG = os.getenv("DEBUG", "false").lower() == "true"')
        lines.append('')

        # Authentication configuration
        lines.append('# Authentication')
        lines.append('DEFAULT_USERNAME = os.getenv("API_USERNAME", "test_user")')
        lines.append('DEFAULT_PASSWORD = os.getenv("API_PASSWORD", "test_password")')
        lines.append('')

        # Test data configuration
        lines.append('# Test data')
        lines.append('TEST_DATA_DIR = os.path.join(os.path.dirname(__file__), "datas")')
        lines.append('')

        # Reporting configuration
        lines.append('# Reporting')
        lines.append('ALLURE_DIR = os.path.join(os.path.dirname(__file__), "allure-results")')
        lines.append('HTML_REPORT_DIR = os.path.join(os.path.dirname(__file__), "html-report")')
        lines.append('')

        return '\n'.join(lines)

    def generate_ini_config(
        self,
        project_name: str = "flowgenius_tests"
    ) -> str:
        """
        Generate pytest.ini configuration file.

        Args:
            project_name: Name of the test project

        Returns:
            Generated pytest.ini content
        """
        lines = [
            '[pytest]',
            '',
            '# Pytest configuration',
            f'minversion = 7.0',
            f'testpaths = testcase',
            f'python_files = test_*.py',
            f'python_classes = Test*',
            f'python_functions = test_*',
            '',
            '# Output options',
            'addopts =',
            '    -v',
            '    --strict-markers',
            '    --tb=short',
            '    --cov=api',
            '    --cov-report=html',
            '    --cov-report=term-missing',
            '    --alluredir=allure-results',
            '',
            '# Markers',
            'markers =',
            '    smoke: Smoke tests',
            '    regression: Regression tests',
            '    api: API tests',
            '    unit: Unit tests',
            '    integration: Integration tests',
            '',
            '# Logging',
            'log_cli = true',
            'log_cli_level = INFO',
            'log_cli_format = %(asctime)s [%(levelname)s] %(message)s',
            'log_cli_date_format = %Y-%m-%d %H:%M:%S',
            '',
        ]

        return '\n'.join(lines)

    def generate_setup_cfg(
        self,
        project_name: str = "flowgenius_tests",
        version: str = "1.0.0"
    ) -> str:
        """
        Generate setup.cfg configuration file.

        Args:
            project_name: Name of the test project
            version: Version string

        Returns:
            Generated setup.cfg content
        """
        lines = [
            '[metadata]',
            f'name = {project_name}',
            f'version = {version}',
            'description = Automated API tests generated by FlowGenius SmartAdapter',
            'long_description = file: README.md',
            'long_description_content_type = text/markdown',
            '',
            '[options]',
            'packages = find:',
            f'python_requires = >=3.8',
            'install_requires =',
            '    requests>=2.31.0',
            '    pytest>=7.4.0',
            '    pytest-cov>=4.1.0',
            '    allure-pytest>=2.13.0',
            '    pyyaml>=6.0',
            '',
            '[options.packages.find]',
            'exclude =',
            '    tests*',
            '    examples*',
            '',
            '[flake8]',
            'max-line-length = 120',
            'exclude =',
            '    .git,',
            '    __pycache__,',
            '    build,',
            '    dist,',
            '    venv,',
            '    .venv,',
            '',
            '[mypy]',
            'python_version = 3.8',
            'warn_return_any = True',
            'warn_unused_configs = True',
            'disallow_untyped_defs = False',
            '',
        ]

        return '\n'.join(lines)

    def generate_pyproject_toml(
        self,
        project_name: str = "flowgenius_tests",
        version: str = "1.0.0"
    ) -> str:
        """
        Generate pyproject.toml configuration file.

        Args:
            project_name: Name of the test project
            version: Version string

        Returns:
            Generated pyproject.toml content
        """
        lines = [
            '[build-system]',
            'requires = ["setuptools>=61.0", "wheel"]',
            'build-backend = "setuptools.build_meta"',
            '',
            '[project]',
            f'name = "{project_name}"',
            f'version = "{version}"',
            'description = "Automated API tests generated by FlowGenius SmartAdapter"',
            'readme = "README.md"',
            'requires-python = ">=3.8"',
            '',
            'dependencies = [',
            '    "requests>=2.31.0",',
            '    "pytest>=7.4.0",',
            '    "pytest-cov>=4.1.0",',
            '    "allure-pytest>=2.13.0",',
            '    "pyyaml>=6.0",',
            ']',
            '',
            '[tool.pytest.ini_options]',
            'minversion = "7.0"',
            'testpaths = ["testcase"]',
            'python_files = ["test_*.py"]',
            'python_classes = ["Test*"]',
            'python_functions = ["test_*"]',
            'addopts = [',
            '    "-v",',
            '    "--strict-markers",',
            '    "--tb=short",',
            '    "--cov=api",',
            '    "--cov-report=html",',
            '    "--alluredir=allure-results",',
            ']',
            'markers = [',
            '    "smoke: Smoke tests",',
            '    "regression: Regression tests",',
            '    "api: API tests",',
            ']',
            '',
            '[tool.black]',
            'line-length = 120',
            'target-version = ["py38", "py39", "py310", "py311"]',
            '',
            '[tool.isort]',
            'profile = "black",',
            'line_length = 120',
            '',
            '[tool.mypy]',
            'python_version = "3.8"',
            'warn_return_any = true',
            'warn_unused_configs = true',
            'disallow_untyped_defs = false',
            '',
        ]

        return '\n'.join(lines)

    def generate_gitignore(self) -> str:
        """Generate .gitignore file."""
        lines = [
            '# Python',
            '__pycache__/',
            '*.py[cod]',
            '*$py.class',
            '*.so',
            '.Python',
            'build/',
            'develop-eggs/',
            'dist/',
            'downloads/',
            'eggs/',
            '.eggs/',
            'lib/',
            'lib64/',
            'parts/',
            'sdist/',
            'var/',
            'wheels/',
            '*.egg-info/',
            '.installed.cfg',
            '*.egg',
            '',
            '# Virtual environments',
            'venv/',
            'ENV/',
            'env/',
            '.venv/',
            '',
            '# IDE',
            '.vscode/',
            '.idea/',
            '*.swp',
            '*.swo',
            '*~',
            '',
            '# Testing',
            '.pytest_cache/',
            '.coverage',
            'htmlcov/',
            'allure-results/',
            'allure-report/',
            '*.cover',
            'htmlcov/',
            '',
            '# Logs',
            '*.log',
            'logs/',
            '',
            '# Generated files',
            'generated/',
            'output/',
            'snapshots/',
            '',
            '# OS',
            '.DS_Store',
            'Thumbs.db',
            '',
            '# Environment',
            '.env',
            '.env.local',
            '',
        ]

        return '\n'.join(lines)

    def generate_all(
        self,
        output_dir: str,
        base_url: str = "https://api.example.com",
        project_name: str = "flowgenius_tests"
    ) -> Dict[str, str]:
        """
        Generate all configuration files.

        Args:
            output_dir: Directory to save files
            base_url: Base URL for API
            project_name: Name of the test project

        Returns:
            Dictionary mapping filenames to file paths
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        results = {}

        # Generate config.py
        config_py = output_path / "config.py"
        config_py.write_text(self.generate_config_py(base_url), encoding='utf-8')
        results["config.py"] = str(config_py)

        # Generate pytest.ini
        pytest_ini = output_path / "pytest.ini"
        pytest_ini.write_text(self.generate_ini_config(project_name), encoding='utf-8')
        results["pytest.ini"] = str(pytest_ini)

        # Generate setup.cfg
        setup_cfg = output_path / "setup.cfg"
        setup_cfg.write_text(self.generate_setup_cfg(project_name), encoding='utf-8')
        results["setup.cfg"] = str(setup_cfg)

        # Generate pyproject.toml
        pyproject_toml = output_path / "pyproject.toml"
        pyproject_toml.write_text(self.generate_pyproject_toml(project_name), encoding='utf-8')
        results["pyproject.toml"] = str(pyproject_toml)

        # Generate .gitignore
        gitignore = output_path / ".gitignore"
        gitignore.write_text(self.generate_gitignore(), encoding='utf-8')
        results[".gitignore"] = str(gitignore)

        self.logger.info(f"Generated {len(results)} configuration files in {output_dir}")
        return results


class EnvConfigBuilder:
    """Builder for environment-specific configurations."""

    def __init__(self):
        """Initialize environment config builder."""
        self.environments: Dict[str, Dict[str, Any]] = {}

    def add_environment(self, name: str, config: Dict[str, Any]):
        """Add an environment configuration."""
        self.environments[name] = config

    def build_default(self):
        """Build default environment configurations."""
        self.add_environment("development", {
            "base_url": "https://dev-api.example.com",
            "timeout": 60,
            "debug": True,
            "retry_count": 5
        })

        self.add_environment("staging", {
            "base_url": "https://staging-api.example.com",
            "timeout": 30,
            "debug": False,
            "retry_count": 3
        })

        self.add_environment("production", {
            "base_url": "https://api.example.com",
            "timeout": 30,
            "debug": False,
            "retry_count": 3
        })

    def get_config(self) -> Dict[str, Dict[str, Any]]:
        """Get all environment configurations."""
        return self.environments